openapi: 3.0.1
info:
  title: Оценка товара
  version: analytics
servers:
  - url: https://seller-analytics-api.wildberries.ru
security:
  - HeaderApiKey: []
tags:
  - name: Оценка товара
    description: ''
paths:
  /api/analytics/v2/item-rating:
    servers:
      - url: https://seller-analytics-api.wildberries.ru
    post:
      x-readonly-method: true
      x-category: contentanalytics
      x-token-types:
        - personal
        - service
      tags:
        - Оценка товара
      summary: Получить отчёт
      operationId: postV2ItemRating
      description: |

        <div class="description_token">
            Метод <a href="/openapi/api-information#tag/authorization/Pravila-ispolzovaniya-tokenov-dostupa-k-API">доступен</a> по
                <strong>Персональному</strong> токену,
                <strong>Сервисному</strong> токену
        </div>

        Метод формирует набор данных об оценках товаров.
        <br><br>
        Данные отчёта обновляются 1 раз в час.

        <div class="description_limit">
        <a href="/openapi/api-information#tag/introduction/Limity-zaprosov">Лимит запросов</a> на один аккаунт продавца:

        | Период | Лимит | Интервал | Всплеск |
        | --- | --- | --- | --- |
        | 1 мин | 3 запроса | 20 сек | 3 запроса |
        </div>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '_schemas.yaml#/components/schemas/ItemRatingRequest'
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '_schemas.yaml#/components/schemas/ItemRatingResponse'
                required:
                  - data
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: '_schemas.yaml#/components/schemas/ErrorObject400'
        '401':
          $ref: '_schemas.yaml#/components/responses/401'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '_schemas.yaml#/components/schemas/ErrorObject403'
            application/problem+json:
              schema:
                $ref: '_schemas.yaml#/components/schemas/Response403General'
        '429':
          $ref: '_schemas.yaml#/components/responses/429'
  /api/analytics/v1/item-rating:
    servers:
      - url: https://seller-analytics-api.wildberries.ru
    post:
      deprecated: true
      x-readonly-method: true
      x-category: contentanalytics
      x-token-types:
        - personal
        - service
      tags:
        - Оценка товара
      summary: Получить отчёт
      operationId: postV1ItemRating
      description: |

        <div class="description_token">
            Метод <a href="/openapi/api-information#tag/authorization/Pravila-ispolzovaniya-tokenov-dostupa-k-API">доступен</a> по
                <strong>Персональному</strong> токену,
                <strong>Сервисному</strong> токену
        </div>

        Данный метод устарел. Он будет удалён [30 июля](/release-notes?id=558).

        <div class="description_limit">
        <a href="/openapi/api-information#tag/introduction/Limity-zaprosov">Лимит запросов</a> на один аккаунт продавца:

        | Период | Лимит | Интервал | Всплеск |
        | --- | --- | --- | --- |
        | 1 мин | 3 запроса | 20 сек | 3 запроса |
        </div>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '_schemas.yaml#/components/schemas/ItemRatingRequestV1'
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '_schemas.yaml#/components/schemas/ItemRatingResponseV1'
                required:
                  - data
        '400':
          description: Неправильный запрос
          content:
            application/json:
              schema:
                $ref: '_schemas.yaml#/components/schemas/ErrorObject400'
        '401':
          $ref: '_schemas.yaml#/components/responses/401'
        '402':
          $ref: '_schemas.yaml#/components/responses/402'
        '403':
          description: Доступ запрещён
          content:
            application/json:
              schema:
                $ref: '_schemas.yaml#/components/schemas/ErrorObject403'
            application/problem+json:
              schema:
                $ref: '_schemas.yaml#/components/schemas/Response403General'
        '429':
          $ref: '_schemas.yaml#/components/responses/429'
components:
  securitySchemes:
    HeaderApiKey:
      type: apiKey
      name: Authorization
      in: header
