openapi: "3.0.1"
info:
  title: Отчёт о товарах c обязательной маркировкой
  version: reports
tags:
  - name: Отчёт о товарах c обязательной маркировкой
    description: ''
servers:
  - url: https://seller-analytics-api.wildberries.ru
security:
  - HeaderApiKey: []
paths:
  /api/v1/analytics/excise-report:
    servers:
      - url: https://seller-analytics-api.wildberries.ru
    post:
      x-readonly-method: true
      x-category: contentanalytics
      tags:
        - Отчёт о товарах c обязательной маркировкой
      summary: Получить отчёт
      description: |
        Метод возвращает отчёт с [операциями по товарам с обязательной маркировкой](https://seller.wildberries.ru/analytics-reports/excise-report).<br><br>

        Данный отчёт можно сохранить в [формате таблиц](https://dev.wildberries.ru/cases/1).

        <div class="description_limit">
        <a href="/openapi/api-information#tag/Vvedenie/Limity-zaprosov">Лимит запросов</a> на один аккаунт продавца:

        | Период | Лимит | Интервал | Всплеск |
        | --- | --- | --- | --- |
        | 5 ч | 10 запросов | 30 мин | 10 запросов |
        </div>
      parameters:
        - $ref: '_schemas.yaml#/components/parameters/DateFrom'
        - $ref: '_schemas.yaml#/components/parameters/DateTo'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '_schemas.yaml#/components/schemas/ExciseReportRequest'
        required: false
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '_schemas.yaml#/components/schemas/ExciseReportResponse'
        '400':
          description: Неправильный запрос
          content:
            application/problem+json:
              schema:
                $ref: '_schemas.yaml#/components/schemas/4xxResponse'
              example:
                detail: 'request body has an error: doesn''t match schema #/components/schemas/ExciseReportRequest: Error at "/countries/0": value is not one of the allowed values ["AM","BY","KG","KZ","RU","UZ"]'
                origin: tariffs
                requestId: 8bbd7db59522d09926dd059892dbeff0
                title: Bad Request
        '401':
          $ref: '_schemas.yaml#/components/responses/401'
        '429':
          $ref: '_schemas.yaml#/components/responses/429'
components:
  securitySchemes:
    HeaderApiKey:
      type: apiKey
      name: Authorization
      in: header
