openapi: "3.0.1"
info:
  title: Продажи по регионам
  version: reports
tags:
  - name: Продажи по регионам
    description: ''
servers:
  - url: https://seller-analytics-api.wildberries.ru
security:
  - HeaderApiKey: []
paths:
  /api/v1/analytics/region-sale:
    servers:
      - url: https://seller-analytics-api.wildberries.ru
    get:
      x-readonly-method: true
      x-category: contentanalytics
      security:
        - HeaderApiKey: []
      tags:
        - Продажи по регионам
      summary: Получить отчёт
      description: |
        Метод возвращает отчёт с [данными продаж, сгруппированных по регионам стран](https://seller.wildberries.ru/analytics-reports/region-sale).<br><br>

        Можно получить отчёт максимум за 31 день.

        <div class="description_limit">
        <a href="/openapi/api-information#tag/Vvedenie/Limity-zaprosov">Лимит запросов</a> на один аккаунт продавца:

        | Период | Лимит | Интервал | Всплеск |
        | --- | --- | --- | --- |
        | 10 сек | 1 запрос | 10 сек | 5 запросов |
        </div>
      parameters:
        - $ref: '_schemas.yaml#/components/parameters/DateFrom'
        - $ref: '_schemas.yaml#/components/parameters/DateTo'
      responses:
        '200':
          $ref: '_schemas.yaml#/components/responses/SuccessRegionSaleResponse'
        '400':
          description: Неправильный запрос
          content:
            application/problem+json:
              schema:
                $ref: '_schemas.yaml#/components/schemas/4xxResponse'
              examples:
                MissingDateTimeFrom:
                  $ref: '_schemas.yaml#/components/examples/MissingDateTimeFrom'
                MissingDateTimeTo:
                  $ref: '_schemas.yaml#/components/examples/MissingDateTimeTo'
                IncorrectDateTimeFrom:
                  $ref: '_schemas.yaml#/components/examples/IncorrectDateTimeFrom'
                IncorrectDateTimeTo:
                  $ref: '_schemas.yaml#/components/examples/IncorrectDateTimeTo'
                DateRangeExceeded:
                  $ref: '_schemas.yaml#/components/examples/DateRangeExceeded'
                DateRanges:
                  $ref: '_schemas.yaml#/components/examples/DateRanges'
        '401':
          $ref: '_schemas.yaml#/components/responses/401'
        '429':
          $ref: '_schemas.yaml#/components/responses/429'
components:
  securitySchemes:
    HeaderApiKey:
      type: apiKey
      name: Authorization
      in: header
